folder_name: testPSGG_PCSM
has_competitor_price: 1
time_bucket: 24
test_dataset_size: 30

features:
  - date
  - net_price
  - day_of_week_n
  - net_price_day_0
  - net_price_day_1
  - net_price_day_2
  - net_price_day_3
  - net_price_day_4
  - net_price_day_5
  - net_price_day_6
  - hour
  # - quantity_ewm_alpha_095_lag_7
  # - FP_quantity_ewm_alpha_095_lag_7
  - FP_quantity_daily_lag2
  # - FP_net_price_daily_lag2
  - trend_daily_lag2
  # - FP_trend_daily_lag2
  - quantity_hourly_lag48
  - quantity_daily_lag4
  - quantity_hourly_lag132
  - quantity_FP_lag48
  - quantity



products:
  # - Apio Est치ndar (Grande) Atado
  # - Cebolla Cabezona Roja Limpia Tama침o Mixto Kg (Tama침o 游)
  # - Cebolla Cabezona Roja Sin Pelar Tama침o Mixto Desde 2Kg
  # - Champi침칩n Blanco Paris 500 gr Bandeja

  # - Fresa Peque침o Kg
  # - Guatila Est치ndar Kg
  # - Papa Criolla Segunda Mixta Kg
  # - Papa Criolla Lavada Semi (Mediana) Kg
  # - Papa Criolla Sin Lavar Tama침o Mixto Kg

  # - Piment칩n Maduraci칩n Mixta Semi (Mediano / Nataly) Desde 2Kg


# # Bad
  - Champi침칩n Blanco Paris 1Kg Bandeja
  # - Fresa Selecta (Grande) Kg
  # - Papa Sabanera Gruesa (Grande) Kg
  # - Papa Sabanera Semi (Mediana) Kg
  # - Rabano Est치ndar Kg 

  # - Champi침칩n Blanco Paris 1Kg Bandeja  - 37
  # - Fresa Selecta (Grande) Kg  - 32
  # - Papa Sabanera Gruesa (Grande) Kg - 53
  # - Papa Sabanera Semi (Mediana) Kg  - 38
  # - Rabano Est치ndar Kg   - mape 42
 
upperBound: 26400
lowerBound: 21121
test_price_step_size: 5
